# Generated by Django 4.0.5 on 2022-06-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='profesion',
        ),
    ]
