# Generated by Django 4.0.5 on 2022-06-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_remove_familia_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='apellido',
            field=models.CharField(default='battaglino', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(default='2022-06-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familia',
            name='profesion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
